### PR TITLE
Initial classes

### PR DESCRIPTION
**Pull request by XedinUnknown**

### CODE REVIEW

**Review by mecha — CHANGES_REQUESTED** [review]
LGTM, but I'd like to see a test for integer normalization in the event of a float overflow (12 decimal place float).

**Comment by XedinUnknown** [comment]
@mecha, perhaps you could add that test, since you're more familiar with the subject?

**Comment by mecha** [comment]
@XedinUnknown Sure. I'll need write access though.

**Comment by XedinUnknown** [comment]
Done, @mecha; sorry about that.

**Comment by XedinUnknown** [comment]
@mecha. genital remindur.

**Comment by mecha** [comment]
@XedinUnknown Oddly enough, the test float `var_dump`s as `float(4)`, and casting it to a string results in `"4"`. But the normalization treats it as a non-whole number and throws. I felt like this was the correct behavior before I wrote this test, but feared that it wouldn't be so. Happy to see that somehow, PHP still retains information about the float, even if it's lost from the code.

**Comment by XedinUnknown** [comment]
@mecha u so naisse. Could you add some docs to the test to explain why we need to test for that at all? Now that I read your latest comment, I can understand that. But I couldn't before.

**Review by mecha — APPROVED** [review]

**Pull request merged**
